apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-demo
spec:
  enablePDB: false
  instances: 1
  imageCatalogRef:
    kind: ImageCatalog
    major: 17
    name: postgresql
    apiGroup: postgresql.cnpg.io
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 1Gi
  storage:
    size: 50Gi
    storageClass: ionos-enterprise-ssd