apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-demo
spec:
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  instances: 3
  imageCatalogRef:
    kind: ImageCatalog
    major: 17
    name: postgresql
    apiGroup: postgresql.cnpg.io
  resources:
    requests:
      cpu: 500m
    limits:
      memory: 1Gi
  storage:
    size: 50Gi
    storageClass: ionos-enterprise-ssd
  walStorage:
    storageClass: ionos-enterprise-ssd
    size: 10Gi
  primaryUpdateMethod: restart
  enablePDB: true
  priorityClassName: high
  monitoring:
    enablePodMonitor: true
